# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7bf55487167b51a19cad65c29b68f65f1c81eb7b6c22922a2dc9d7f304ea5f6eb85f70b2a4fa0332ab257abc5a2544399672e8aec1fbc303600d8fb380b5dbf

test:
  secret_key_base: 044d18b9b874967165ec2f1a5a1ab7fa61ca85eb7eaf90253831c5386e1d9c85fb92cbbbdfa8199661ae245d5ee98e20fc5881a16acd37b63f85ac352bd6b954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
